//
//  FruitsAndBerriesModels.swift
//  FruitsAndBerries
//
//  Created by Igor Palyvoda on 03.01.2024.
//

import UIKit

enum FruitsAndBerriesModels {
    // Models for "load (list)" use case
    struct Load {
        // Response is passed from Interactor to Presenter
        struct Response: Decodable {
            let title: String
            let items: [FruitsAndBerriesItem]
            
            struct FruitsAndBerriesItem: Decodable {
                let id: String
                let name: String
                let image: URL?
                let color: String
            }
        }
        
        // View model is generated by Presenter and passed to View
        struct ViewModel {
            let title: String
            let items: [FruitsAndBerriesViewModelItem]
            
            struct FruitsAndBerriesViewModelItem {
                let id: String
                let name: String
                let imageURL: URL?
                let color: String
            }
        }
    }
    
    struct LoadDetails {
        // Models for "load details" use case
        struct Request {
            let itemId: String
        }
        // View model is generated by Presenter and passed to View
        struct Response: Decodable {
            let id: String
            let text: String
        }
        
        // View model is generated by Presenter and passed to View
        struct DetailViewModel {
            let text: String
        }
    }
}
